apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.api.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.config.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.api.name }}
    spec:
      containers:
      - name: {{ .Values.config.api.name }}
        image: {{ .Values.config.api.image }}
        ports:
        - containerPort: 5000
        env:
        - name: URL_BIO
          value: "https://api.biorxiv.org/covid19/"
        - name: RABBITMQ
          value: "databases-rabbitmq"
        - name: RABBITMQ_QUEUE
          value: "queue"
        - name: RABBITMQ_QUEUE_DST
          value: "downloaded"
        - name: RABBITMQ_USER
          value: "user"
        - name: XPATH
          value: "/data"
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: databases-rabbitmq
              key: rabbitmq-password
              optional: false
        - name: OUTPUT_DIR
          value: "/mnt/shared/raw"
        volumeMounts:
        - name: shared-storage
          mountPath: /mnt/shared
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc